# Generated by Django 4.2.7 on 2026-02-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentlyWorking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What are you building/learning?', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('building', 'Building'), ('learning', 'Learning'), ('contributing', 'Contributing'), ('reading', 'Reading')], default='building', max_length=50)),
                ('tech_tags', models.JSONField(default=list, help_text='["FastAPI","LangChain"]')),
                ('link', models.URLField(blank=True)),
                ('progress', models.IntegerField(default=0, help_text='0-100 percent')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currently Working On',
                'verbose_name_plural': 'Currently Working On',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('problem', models.TextField(blank=True, help_text='What problem does it solve?')),
                ('outcome', models.TextField(blank=True, help_text='Measurable result e.g. 40% faster')),
                ('demo_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('tech_stack', models.JSONField(default=list, help_text='["Django","PostgreSQL","Redis"]')),
                ('github_stars', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
