# Generated by Django 4.2.7 on 2026-08-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_currentlyworking_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Must match a scenario key in architecture-lab.js, e.g. 'notification'", unique=True)),
                ('number', models.CharField(help_text="e.g. '01'", max_length=10)),
                ('difficulty', models.CharField(help_text="e.g. 'SENIOR / SYSTEM DESIGN'", max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirement_chips', models.JSONField(default=list, help_text='["10M events/day","Retries + dedupe"]')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
