# Generated by Django 4.2.7 on 2026-08-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureDecisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text="e.g. 'ADR-001'", max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('detail', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ADR',
                'verbose_name_plural': 'ADRs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Must match a StageNode name, e.g. 'KAFKA'", max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('problem', models.TextField()),
                ('decision', models.TextField()),
                ('tradeoff', models.TextField()),
                ('alternatives', models.TextField()),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('problem', models.TextField()),
                ('decision', models.TextField()),
                ('detail', models.TextField()),
                ('alternatives', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FailureMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Kafka goes down'", max_length=200)),
                ('impact', models.CharField(max_length=200)),
                ('response', models.TextField()),
                ('recovery', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SimulatorBottleneck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveIntegerField(unique=True)),
                ('text', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['tier'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('requirements', 'Requirements'), ('initial', 'Start Simple'), ('bottleneck', 'Find Limits'), ('evolved', 'Evolve')], max_length=20)),
                ('mode', models.CharField(help_text="e.g. 'FOUNDATION'", max_length=100)),
                ('title', models.CharField(help_text="e.g. '01 — Frame the constraints'", max_length=200)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrafficMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(help_text='0-3, matches the traffic slider position', unique=True)),
                ('traffic_label', models.CharField(help_text="e.g. '10K events/day'", max_length=50)),
                ('events', models.CharField(help_text="e.g. '10,000'", max_length=50)),
                ('throughput', models.CharField(max_length=50)),
                ('latency', models.CharField(max_length=50)),
                ('error_rate', models.CharField(max_length=50)),
                ('queue_lag', models.CharField(max_length=50)),
                ('db_load', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='journey_title',
            field=models.CharField(blank=True, help_text="Heading shown once the scenario is opened, e.g. 'Notification delivery, from first principles.'", max_length=200),
        ),
        migrations.CreateModel(
            name='StagePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='portfolio.stage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StageNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Must match a Component name to power the inspector, e.g. 'KAFKA'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='portfolio.stage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='portfolio.scenario'),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('scenario', 'key')},
        ),
        migrations.CreateModel(
            name='SimulatorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveIntegerField(help_text='0-3, matches the computed pressure tier')),
                ('name', models.CharField(max_length=200)),
                ('diagram', models.TextField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulator_plans', to='portfolio.scenario')),
            ],
            options={
                'ordering': ['tier'],
                'unique_together': {('scenario', 'tier')},
            },
        ),
    ]
