# Generated by Django 4.2.7 on 2026-08-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_architecturedecisionrecord_component_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='is_core',
            field=models.BooleanField(default=True, help_text='Shown in the featured "Core Expertise" row vs a compact secondary row'),
        ),
    ]
